[tool.black]
line-length = 100
target_version = ['py37', 'py38']
skip-magic-trailing-comma = true

[tool.isort]
profile = 'black'
# Sort alphabetically, irrespective of case.
order_by_type = false
line_length = 100
remove_redundant_aliases = true
